
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    tier: db
    project: roboshop
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb
    tier: db
    project: roboshop
    