apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    tier: db
    project: roboshop
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: db
      project: roboshop # has to match .spec.template.metadata.labels
  serviceName: "mongodb"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mongodb
        image: joindevops787/mongodb:{{ .Values.statefulset.imageVersion }}
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
