apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    tier: db
    project: roboshop
spec:
  selector:
    matchLabels:
      app: rabbitmq
      tier: db
      project: roboshop # has to match .spec.template.metadata.labels
  serviceName: "rabbitmq"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: rabbitmq
        tier: db
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    tier: db
    project: roboshop
spec:
  clusterIP: None
  selector: 
    app: rabbitmq
    tier: db
    project: roboshop
  ports:
    - name: rabbitmq-port
      protocol: TCP
      port: 5672
      targetPort: 5672