apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
    tier: db
    project: roboshop
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  clusterIP: None
  selector:
    app: redis
    tier: db
    project: roboshop
    