apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
    tier: db
    project: roboshop
spec:
  selector:
    matchLabels:
      app: redis
      tier: db
      project: roboshop # has to match .spec.template.metadata.labels
  serviceName: "redis"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: redis
        tier: db
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: redis
        volumeMounts:
        - name: redis
          mountPath: /data
      volumes:
      - name: redis
        persistentVolumeClaim:
            ClaimName: ebs-redis-pvc 
 