apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
    tier: db
    project: roboshop
spec:
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: roboshop # has to match .spec.template.metadata.labels
  serviceName: "mysql"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: joindevops787/mysql:1.0.0
        envFrom:
        - configMapRef:
            name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    tier: db
    project: roboshop
spec:
  clusterIP: None
  selector: 
    app: mysql
    tier: db
    project: roboshop
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306
      targetPort: 3306  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"
  MYSQL_PASSWORD: "RoboShop@1"


 
    