apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
    tier: db
    project: roboshop
spec:
  selector:
    matchLabels:
      app: redis
      tier: db
      project: roboshop # has to match .spec.template.metadata.labels
  serviceName: "redis"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: redis
        tier: db
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: redis
        volumeMounts:
        - name: redis
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    tier: db
    project: roboshop
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  clusterIP: None
  selector:
    app: redis
    tier: db
    project: roboshop
    